account/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='account'


urlpatterns = [
    path('', views.admin_users, name='admin_users'),
    path('create_admin/', views.create_admin, name='create_admin'),
    path('users', views.users, name='users'),
    path('create_user/', views.create_user, name='create_user'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

core/urls.py
from django.urls import path
from . import views

app_name='core'


urlpatterns = [
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout'),
    path('', views.index, name='index'),
    path('reward/', views.reward, name='reward'),
    path('settings/', views.settings, name='settings'),
    path('privacy/', views.privacy_edit, name='privacy'),
    path('conditions/', views.conditions_edit, name='conditions'),
    path('credits/', views.credits_edit, name='credits'),
]

reward/urls.py
from django.urls import path
from . import views

app_name = 'reward'

urlpatterns = [
    path('trophies/', views.trophies, name="trophies"),
    path('trophies/detail/<int:id>/', views.trophy_detail, name="trophy_detail"),
    path('trophies/create/', views.create_trophy, name="create_trophy"),
    path('trophies/update/<int:id>/', views.update_trophy, name="update_trophy"),
    path('trophies/delete/<int:id>/', views.delete_trophy, name="delete_trophy"),
    path('magic_box/', views.magic_boxes, name="magic_boxes"),
    path('magic_box/<int:id>/', views.magic_box_detail, name="magic_box_detail"),
    path('magic_box/create/', views.create_magic_boxes, name="create_magic_box"),
    path('magic_box/update/<int:id>/', views.update_magic_boxes, name="update_magic_box"),
    path('magic_box/delete/<int:id>/', views.delete_magic_boxes, name="delete_magic_box"),
]

trend/urls.py
from django.contrib import admin
from django.urls import path, include

from core.api import api_views as core_views
import core

from account.api import api_views as account_views

from game.api import api_views as game_views

from post.api import api_views as post_views

from product.api import api_views as product_views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('account/', include('account.urls', namespace='account')),
    path('game/', include('game.urls', namespace='game')),
    path('post/', include('post.urls', namespace='post')),
    path('product/', include('product.urls', namespace='product')),
    path('reward/', include('reward.urls', namespace='reward')),

    
    path('password-reset/', auth_views.PasswordResetView.as_view(
        form_class = core.forms.CustomPasswordResetForm,
        template_name='core/password_reset.html',
        html_email_template_name = 'core/password_reset_html_email.html',
        subject_template_name = 'core/password_reset_subject.txt',
        from_email = 'support@trend.com'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
    ), name='password_reset_confirm'),

    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name = 'core/password_reset_complete.html'
    ), name='password_reset_complete'),

]

# API Endpoints

urlpatterns += [
	path('api/v1/login/', account_views.LoginView.as_view()),
    path('api/v1/logout/', account_views.LogoutView.as_view()),
    path('api/v1/register/', account_views.RegisterView.as_view()),
    path('api/v1/fbregister/', account_views.FacebookRegisterView.as_view()),
    path('api/v1/apple-register/', account_views.AppleRegisterAPIView.as_view()),
    path('api/v1/getverified/', account_views.GetVerifiedAPIView.as_view()),
    path('api/v1/forgotpassword/', account_views.ForgotPasswordAPIView.as_view()),
    path('api/v1/codeverification/', account_views.CodeVerificationAPIView.as_view()),
    path('api/v1/newpassword/', account_views.NewPasswordAPIView.as_view()),
    path('api/v1/updatepassword/', account_views.UpdatePasswordAPIView.as_view()),

    path('api/v1/profile/', core_views.ProfileAPIView.as_view()),
    path('api/v1/profile/follow/', core_views.FollowAPIView.as_view()),
    path('api/v1/profile/followings/', core_views.FollowingsAPIView.as_view()),
    path('api/v1/profile/dp/', core_views.ProfielDPAPIView.as_view()),
    path('api/v1/profile/update/', core_views.ProfileUpdateAPIView.as_view()),
    path('api/v1/getlist/', core_views.GetListAPIView.as_view()),
    path('api/v1/invite/', core_views.InviteAPIView.as_view()),
    path('api/v1/privacy/', core_views.PrivacyAPIView.as_view()),
    path('api/v1/conditions/', core_views.ConditionsAPIView.as_view()),
    path('api/v1/credits/', core_views.CreditsAPIView.as_view()),
    path('api/v1/completed-tours/', core_views.CompletedToursAPIView.as_view()),
    path('api/v1/ongoing-tours/', core_views.RunningToursAPIView.as_view()),

    path('api/v1/classic/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/games/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/event/', game_views.GameEventAPIView.as_view()),
    path('api/v1/game/single/', game_views.GameDetailAPIView),
    path('api/v1/game/join/', game_views.GameJoinAPIView),
    path('api/v1/challenge/', game_views.ChallengeDetailAPIView.as_view()),
    path('api/v1/joinevent/', game_views.JoinEventAPIView.as_view()),
    path('api/v1/submitchallenge/', game_views.SubmitChallengeAPIView.as_view()),
    path('api/v1/ranking/', game_views.RankingAPIView.as_view()),

    path('api/v1/product/', product_views.ProductAPIView.as_view()),
    path('api/v1/product/single/', product_views.ProductDetailView.as_view()),
    path('api/v1/product/buy/', product_views.ProductBuyView.as_view()),

    path('api/v1/post/', post_views.PostView.as_view()),
    path('api/v1/post/single/', post_views.PostDetailView.as_view()),
    path('api/v1/post/user/', post_views.UserPostAPIView),
    path('api/v1/post/create/', post_views.create_post),
    path('api/v1/post/edit/', post_views.edit_post),
    path('api/v1/comment/create/', post_views.create_comment),
    path('api/v1/comment/delete/', post_views.delete_comment),
    path('api/v1/like/', post_views.add_like),
]



handler404 = core.views.handle404
handler500 = core.views.handle500

# For media files like images
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

from account.models import MyUser
from game.models import Game, Challenge

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'uploads/profile/user_{0}/dp/{1}'.format(instance.user.id, filename)

def user_directory_game_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'uploads/profile/user_{0}/{1}/{2}'.format(instance.user.id, instance.challenge.title, filename)

class MyModel(models.Model):
    upload = models.FileField(upload_to=user_directory_path)

class Profile(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE)
    latitude = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True)
    image = models.ImageField(upload_to=user_directory_path, default='uploads/profile/default.jpeg')
    following = models.ManyToManyField(MyUser, default=None, blank=True, related_name='following')
    credits = models.IntegerField(default=0)

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

    @property
    def posts(self):
        return self.user.post_set.filter(is_approved=True)[:4]

    @property
    def posted(self):
        return self.user.post_set.filter(is_approved=True).count()

    def email(self):
        return self.user.email

class UserGame(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, related_name='usergame')
    game_tours = models.ManyToManyField(Game, default=None, blank=True, related_name='game_tours')
    challenges = models.ManyToManyField(Challenge, default=None, blank=True, related_name='challenges')

    def __str__(self):
        return str(self.profile)

    @property
    def profile_user_id(self):
        return self.profile.user.id

    @property
    def games(self):
        return self.game_tours.all().count()

class UserChallenge(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=user_directory_game_path)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} {}'.format(self.profile, self.challenge)

class Reward(models.Model):
    welcome = models.IntegerField()
    per_post = models.IntegerField()

    def __str__(self):
        return 'Welcome Reward {} & Per Post Reward {}'.format(int(self.welcome), int(self.per_post))


class SubmitChallenge(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='submitchallenges')
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=user_directory_game_path)
    created_at = models.DateTimeField(auto_now_add=True)
    points = models.IntegerField()

    def __str__(self):
        return '{} for {} in {} challenge'.format(self.user, self.game, self.challenge)
    
    @property
    def username(self):
        return str(self.user.first_name, self.user.last_name)


RECEIVED_CHOICES = (
    ('content', 'content'),
    ('submission', 'submission')
)

class ReceivedPoint(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='points_received')
    points = models.IntegerField()
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True, blank=True)
    received_for = models.CharField(max_length=20, choices=RECEIVED_CHOICES)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {}'.format(self.user, self.points)

    def save(self, *args, **kwargs):
        self.game = self.challenge.game
        return super(ReceivedPoint, self).save(*args, **kwargs)


class Privacy(models.Model):
    text = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Privacy'
        verbose_name_plural = 'Privacy'

    def __str__(self):
        return '{}...'.format(self.text[:20])


class Conditions(models.Model):
    text = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Conditions'
        verbose_name_plural = 'Conditions'

    def __str__(self):
        return '{}...'.format(self.text[:20])


class Credits(models.Model):
    text = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Credits'
        verbose_name_plural = 'Credits'

    def __str__(self):
        return '{}...'.format(self.text[:20])

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from core.models import Reward, Privacy, Conditions, Credits
from account.models import MyUser
from product.models import Product
from game.models import Game, Challenge

from core.forms import RewardForm, CustomPasswordResetForm, PrivacyForm, ConditionsForm, CreditsForm

from django.contrib.auth import authenticate, login, logout

from trend.decorators import admin_only

import geocoder
from .haversine import distance

def loginview(request):
    if request.POST:
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None and user.is_admin:
            login(request, user)
            return redirect('core:index')
        else:
            messages.error(request, f"Le credenziali non corrispondono a nessun utente!")
            return redirect('core:login')
    return render(request, 'core/login.html')


def logoutview(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('core:login')

def nearest_location(request):
    users = MyUser.objects.all()[:5]
    products = Product.objects.all().order_by('-basket')[:5]
    game = Game.objects.all().first()
    d_lat = float(game.location_latitude)
    d_lon = float(game.location_longitude)
    print(d_lat, d_lon)
    print('***********************************************')
    ip = request.META.get('REMOTE_ADDR')
    g = geocoder.ip('45.115.253.178')
    s_lat = g.latlng[0]
    s_lon = g.latlng[1]
    print(s_lat, s_lon)

    # Calculating distance using Haversine 
    dis = distance(d_lat, d_lon, s_lat, s_lon)
    print(dis)

    context = {
        'users': users,
        'products': products
    }
    return render(request, 'core/index.html', context)


@admin_only
def index(request):
    users = MyUser.objects.filter(is_admin=False).count()
    games = Game.objects.all().count()
    challenges = Challenge.objects.all().count()
    reward = Reward.objects.all()
    if reward:
        reward = reward.first()
    else:
        reward = Reward.objects.create(welcome=100, per_post=5)

    context = {
        'users': users,
        'games': games,
        'challenges': challenges,
        'reward': reward
    }
    return render(request, 'core/dashboard.html', context)


def reward(request):
    reward = Reward.objects.all().first()
    if request.POST:
        form = RewardForm(request.POST, instance=reward)
        if form.is_valid():
            form.save()
            messages.success(request, f"i punti premio sono stati aggiornati con successo!")
            return redirect('core:index')
    else:
        form = RewardForm(instance=reward)

    context = {
        'form': form,
        'reward': reward
    }
    return render(request, 'core/reward.html', context)


def settings(request):
    privacy = Privacy.objects.all().first()
    conditions = Conditions.objects.all().first()
    initial_credits = Credits.objects.all().first()
    context = {
        'privacy': privacy,
        'conditions': conditions,
        'credits': initial_credits
    }
    return render(request, 'core/settings.html', context)


def privacy_edit(request):
    privacy = Privacy.objects.all().first()
    print(privacy)
    if request.POST:
        form = PrivacyForm(request.POST, instance=privacy)
        if form.is_valid():
            form.save()
            messages.success(request, f"La Privacy Policy è stata aggiornata!")
            return redirect('core:settings')
    else:
        form = PrivacyForm(instance=privacy)

    context = {
        'form': form,
        'privacy': privacy
    }
    return render(request, 'core/privacy.html', context)


def conditions_edit(request):
    conditions = Conditions.objects.all().first()
    if request.POST:
        form = ConditionsForm(request.POST, instance=conditions)
        if form.is_valid():
            form.save()
            messages.success(request, f"Le condizioni sono state aggiornate!")
            return redirect('core:settings')
    else:
        form = ConditionsForm(instance=conditions)

    context = {
        'form': form,
        'conditions': conditions
    }
    return render(request, 'core/conditions.html', context)


def credits_edit(request):
    initial_credits = Credits.objects.all().first()
    if request.POST:
        form = CreditsForm(request.POST, instance=initial_credits)
        if form.is_valid():
            form.save()
            messages.success(request, f"I crediti sono stati aggiornati!")
            return redirect('core:settings')
    else:
        form = CreditsForm(instance=initial_credits)

    context = {
        'form': form,
        'credits': initial_credits
    }
    return render(request, 'core/credits.html', context)


# 404 and 500 Handlers

def handle404(request, exception):
    return render(request, 'core/404.html', status=404)

def handle500(request, *args, **argv):
    return render(request, 'core/404.html', status=500)

templates/core/conditions.html
{% extends 'base.html' %}

{% block title %}
<title>Termini e condizioni</title>
{% endblock title %}



{% block content %}

<div class="m-t-82">
	<div class="page_content">
		<div class="vendor_outer">

			<div class="vendor_title">
				<h4>Termini e condizioni</h4>

			</div>
			<div class="link_box">
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}

					<p>
						<textarea name="text" cols="60" rows="10" id="id_text" >{{ form.text.value }}</textarea>
					</p>

					<button type="submit" class="btn btn-primary">inviare le modifiche</button>
				</form>

			</div>
		</div>
	</div>
	<div class="footer">
		<p>Copyright © 2020. </p>
	</div>
</div>
{% endblock content %}

{% block script %}
<script>
	var labels = document.getElementsByTagName('label')
	var inputs = document.getElementsByTagName('input')

	for (i = 0; i < inputs.length; i++) {
		inputs[i].className += 'form-control'
	}

</script>
{% endblock script %}

templates/core/credits.html
{% extends 'base.html' %}

{% block title %}
<title>Credits</title>
{% endblock title %}



{% block content %}

<div class="m-t-82">
	<div class="page_content">
		<div class="vendor_outer">

			<div class="vendor_title">
				<h4>Credits</h4>

			</div>
			<div class="link_box">
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}

					<p>
						<textarea name="text" cols="60" rows="10" id="id_text" >{{ form.text.value }}</textarea>
					</p>

					<button type="submit" class="btn btn-primary">inviare le modifiche</button>
				</form>

			</div>
		</div>
	</div>
	<div class="footer">
		<p>Copyright © 2020. </p>
	</div>
</div>
{% endblock content %}

{% block script %}
<script>
	var labels = document.getElementsByTagName('label')
	var inputs = document.getElementsByTagName('input')

	for (i = 0; i < inputs.length; i++) {
		inputs[i].className += 'form-control'
	}

</script>
{% endblock script %}

templates/core/dashboard.html
{% extends 'base.html' %}

{% block title %}
<title>Pannello di controllo</title>
{% endblock title %}


{% block content %}
				
				<div class="m-t-82">
					<div class="page_content">
					{% if messages %}
						{% for message in messages %}
							{{ message }}
						{% endfor %}
					{% endif %}
						<div class="link_box">
							<ul class="d-flex flex-wrap">
								<li>
									<a href="{% url 'game:index' %}">
										<h4>Giochi totali</h4>
										<h1 class="blue">{{ games }}</h3>
										<p>Tour del gioco</p>
										<form action="{% url 'game:index' %}">
											{% csrf_token %}
										<button class="btn btn-dark-blue" >DETTAGLI</button>
										</form>
									</a>
								</li>
								
								<li>
									<a href="{% url 'game:index' %}">
										
										<h4>Sfide totali</h4>
										<h1 class="pink">{{ challenges }}</h3>
										<p>Sfide</p>
										<form action="{% url 'game:index' %}">
											{% csrf_token %}
										<button class="btn btn-dark-blue" >DETTAGLI</button>
										</form>
									</a>
								</li>
								<li>
									<a href="{% url 'account:users' %}">
										
										<h4>Utenti totali</h4>
										<h1 class="green">{{ users }}</h1>
										<p>Utenti</p>
										<form action="{% url 'account:admin_users' %}">
											{% csrf_token %}
										<button class="btn btn-dark-blue" >DETTAGLI</button>
										</form>
									</a>
								</li>
								
								<li>
									<a href="{% url 'core:reward' %}">
										
										<h4>Benvenuto Punti:</h4>
										<h1 class="green">{{ reward.welcome }}</h1>
										<p>benvenuta</p>
										<form action="{% url 'core:reward' %}">
											{% csrf_token %}
										<button class="btn btn-dark-blue" >Edit</button>
										</form>
									</a>
								</li>
								
								<!-- <li>
									<a href="{% url 'core:reward' %}">
										
										<h4>Pubblica punti:</h4>
										<h1 class="blue">{{ reward.per_post }}</h1>
										<p>Pubblica</p>
										<form action="{% url 'core:reward' %}">
											{% csrf_token %}
										<button class="btn btn-dark-blue" >Edit</button>
										</form>
									</a>
								</li> -->
							</ul>
						</div>
					</div>
					<div class="footer">
						<p>Copyright © 2020. </p>
					</div>
				</div>
{% endblock content %}

{% block script %}
<script>
	var inputs = document.getElementsByTagName('input');

	for(i=0;i<inputs.length;i++){
		inputs[i].className += 'form-control'
	}
</script>
{% endblock script %}

templates/core/login.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Trend</title>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'css/fonts/font.css' %}" type="text/css" rel="stylesheet">
	</head>
	<body>
		<div class="login_outer">
			<div class="login_inner  d-flex flex-wrap">
				<div class="login_left">
					<a href="#">
						<img src="{% static 'images/logo.png' %}" alt="">
						
					</a>
				</div>
				<div class="login_right">
					<div class="login_text">
						{% if messages %}
						{% for message in messages %}
							{% if message|cut:" " == "Youhavetologinfirst!" %}
								<p>Devi prima effettuare il login!</p>
							{% else %}
								<p>{{ message }}</p>
							{% endif %}
						{% endfor %}
						{% endif %}
						<h3>Accedi qui per continuare.</h3>
						
						<div class="login_form">
							<form method="post">
								{% csrf_token %}
								{{ form.errors }}
								<div class="login_group_outer">
								
									<div class="login_group">
										
										<input type="email" class="form-control" placeholder="La tua email" name="email">
									</div>
								</div>
								<div class="login_group_outer">
									
									<div class="login_group">
										
										<input type="password" class="form-control" placeholder="La tua password" name="password">
									</div>
								</div>
								<div class="login_btn">
									<button class="btn btn-light-blue btn-blue-hover" type="submit">Invia</button>
								</div>
							</form>
							<div class="forgot_pass">
								<p>Ha dimenticato la password?<a href="{% url 'password_reset' %}">Fare clic qui per ripristinare</a></p>
							</div>
							
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
	</body>
</html>

templates/core/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Trend</title>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'css/fonts/font.css' %}" type="text/css" rel="stylesheet">
	</head>
	<body>
		<div class="login_outer">
			<div class="login_inner  d-flex flex-wrap">
				<div class="login_left">
					<a href="#">
						<img src="{% static 'images/logo.png' %}" alt="">
						
					</a>
				</div>
				<div class="login_right">
					<div class="login_text">
                        <h3>Email inviata</h3>
                        <p>È stata inviata un'e-mail con le istruzioni per reimpostare la password</p>
                    </div>
				</div>
			</div>
		</div>
		<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
	</body>
</html>

templates/core/privacy.html
{% extends 'base.html' %}

{% block title %}
<title>Trattamento della Privacy</title>
{% endblock title %}



{% block content %}

<div class="m-t-82">
	<div class="page_content">
		<div class="vendor_outer">

			<div class="vendor_title">
				<h4>Trattamento della Privacy</h4>

			</div>
			<div class="link_box">
				<form method="POST">
					{% csrf_token %}
					<p>
						<textarea name="text" cols="60" rows="10" id="id_text" >{{ form.text.value }}</textarea>
					</p>

					<button type="submit" class="btn btn-primary">inviare le modifiche</button>
				</form>

			</div>
		</div>
	</div>
	<div class="footer">
		<p>Copyright © 2020. </p>
	</div>
</div>
{% endblock content %}

{% block script %}
<script>
	var labels = document.getElementsByTagName('label')
	var inputs = document.getElementsByTagName('input')

	for (i = 0; i < inputs.length; i++) {
		inputs[i].className += 'form-control'
	}

</script>
{% endblock script %}

templates/core/reward.html
{% extends 'base.html' %}

{% block title %}
<title>Modifica punti premio</title>
{% endblock title %}



{% block content %}

<div class="m-t-82">
	<div class="page_content">
		<div class="vendor_outer">

			<div class="vendor_title">
				<h4>Aggiorna i punti premio</h4>

			</div>
			<div class="link_box">
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}

					<p>
						<label for="id_welcome">Benvenuta:</label>
						<input type="number" name="welcome" value="{{ form.welcome.value }}" required id="id_welcome"></p>
					<!-- <p><label for="id_per_post">Per post:</label> <input type="number" name="per_post" value="5"
							required id="id_per_post"></p> -->
					<div id="map"></div>

					<button type="submit" class="btn btn-primary">Aggiorna punti</button>
				</form>

			</div>
		</div>
	</div>
	<div class="footer">
		<p>Copyright © 2020. </p>
	</div>
</div>
{% endblock content %}

{% block script %}
<script>
	var labels = document.getElementsByTagName('label')
	var inputs = document.getElementsByTagName('input')

	for (i = 0; i < inputs.length; i++) {
		inputs[i].className += 'form-control'
	}

</script>
{% endblock script %}

templates/core/settings.html
{% extends 'base.html' %}

{% block title %}
<title>impostazioni</title>
{% endblock title %}



{% block content %}
	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			{% if messages %}
				{% for message in messages %}
					{{ message }}
				{% endfor %}
			{% endif %}
			<div class="vendor_title">
					<h4>impostazioni</h4>
				</div>
			<div class="link_box">
			
			<table id="example" class="table table-striped table-bordered" style="width:100%">
			<thead>
			<tr>
			<th>impostazioni </th>
			<th>Testo </th>
			<th></th>
			</tr>
			</thead>
			<tbody>
			
			<tr>
			<td>Privacy</td>
			<td>{{ privacy.text|truncatechars:60 }}</td>
			<td>
			<a href="{% url 'core:privacy' %}"><i class="fa fa-edit" aria-hidden="true"></i></a> &nbsp;&nbsp;
			</td>
			</tr>


			<tr>
			<td>Conditions</td>
			<td>{{ conditions.text|truncatechars:60 }}</td>
			<td>
			<a href="{% url 'core:conditions' %}"><i class="fa fa-edit" aria-hidden="true"></i></a>&nbsp;&nbsp;
			</td>
			</tr>


			<tr>
			<td>Credits</td>
			<td>{{ credits.text|truncatechars:60 }}</td>
			<td>
			<a href="{% url 'core:credits' %}"><i class="fa fa-edit" aria-hidden="true"></i></a> &nbsp;&nbsp;
			</td>
			</tr>
			
			
			</tbody>
			</table>
			
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>
{% endblock content %}

{% block script %}
<script>
	document.getElementById('example_length').style.display = "none";
</script>
{% endblock script %}