core/urls.py
from django.urls import path
from . import views

app_name='core'


urlpatterns = [
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout'),
    path('', views.index, name='index'),
    path('reward/', views.reward, name='reward'),
    path('settings/', views.settings, name='settings'),
    path('privacy/', views.privacy_edit, name='privacy'),
    path('conditions/', views.conditions_edit, name='conditions'),
    path('credits/', views.credits_edit, name='credits'),
]

game/urls.py
from django.urls import path
from . import views

app_name='game'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.single, name='single'),
    path('creategame/', views.create_game, name='create_game'),
    path('editgame/<int:id>/', views.edit_game, name='edit_game'),
    path('deletegame/<int:id>/', views.delete_game, name='delete_game'),

    path('<int:id>/challenge/', views.challenge, name='challenge'),
    path('singlechallenge/<int:id>/', views.single_challenge, name='single_challenge'),
    path('<int:id>/createchallenge/', views.create_challenge, name='create_challenge'),
    path('editchallenge/<int:id>/', views.edit_challenge, name='edit_challenge'),
    path('deletechallenge/<int:id>/', views.delete_challenge, name='delete_challenge'),

    path('promotion/create/<int:id>/', views.create_promotion, name='create_promotion'),
    path('promotion/edit/<int:id>/', views.edit_promotion, name='edit_promotion'),
    path('promotion/delete/<int:id>/', views.delete_promotion, name='delete_promotion')
]

trend/urls.py
from django.contrib import admin
from django.urls import path, include

from core.api import api_views as core_views
import core

from account.api import api_views as account_views

from game.api import api_views as game_views

from post.api import api_views as post_views

from product.api import api_views as product_views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('account/', include('account.urls', namespace='account')),
    path('game/', include('game.urls', namespace='game')),
    path('post/', include('post.urls', namespace='post')),
    path('product/', include('product.urls', namespace='product')),
    path('reward/', include('reward.urls', namespace='reward')),

    
    path('password-reset/', auth_views.PasswordResetView.as_view(
        form_class = core.forms.CustomPasswordResetForm,
        template_name='core/password_reset.html',
        html_email_template_name = 'core/password_reset_html_email.html',
        subject_template_name = 'core/password_reset_subject.txt',
        from_email = 'support@trend.com'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
    ), name='password_reset_confirm'),

    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name = 'core/password_reset_complete.html'
    ), name='password_reset_complete'),

]

# API Endpoints

urlpatterns += [
	path('api/v1/login/', account_views.LoginView.as_view()),
    path('api/v1/logout/', account_views.LogoutView.as_view()),
    path('api/v1/register/', account_views.RegisterView.as_view()),
    path('api/v1/fbregister/', account_views.FacebookRegisterView.as_view()),
    path('api/v1/apple-register/', account_views.AppleRegisterAPIView.as_view()),
    path('api/v1/getverified/', account_views.GetVerifiedAPIView.as_view()),
    path('api/v1/forgotpassword/', account_views.ForgotPasswordAPIView.as_view()),
    path('api/v1/codeverification/', account_views.CodeVerificationAPIView.as_view()),
    path('api/v1/newpassword/', account_views.NewPasswordAPIView.as_view()),
    path('api/v1/updatepassword/', account_views.UpdatePasswordAPIView.as_view()),

    path('api/v1/profile/', core_views.ProfileAPIView.as_view()),
    path('api/v1/profile/follow/', core_views.FollowAPIView.as_view()),
    path('api/v1/profile/followings/', core_views.FollowingsAPIView.as_view()),
    path('api/v1/profile/dp/', core_views.ProfielDPAPIView.as_view()),
    path('api/v1/profile/update/', core_views.ProfileUpdateAPIView.as_view()),
    path('api/v1/getlist/', core_views.GetListAPIView.as_view()),
    path('api/v1/invite/', core_views.InviteAPIView.as_view()),
    path('api/v1/privacy/', core_views.PrivacyAPIView.as_view()),
    path('api/v1/conditions/', core_views.ConditionsAPIView.as_view()),
    path('api/v1/credits/', core_views.CreditsAPIView.as_view()),
    path('api/v1/completed-tours/', core_views.CompletedToursAPIView.as_view()),
    path('api/v1/ongoing-tours/', core_views.RunningToursAPIView.as_view()),

    path('api/v1/classic/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/games/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/event/', game_views.GameEventAPIView.as_view()),
    path('api/v1/game/single/', game_views.GameDetailAPIView),
    path('api/v1/game/join/', game_views.GameJoinAPIView),
    path('api/v1/challenge/', game_views.ChallengeDetailAPIView.as_view()),
    path('api/v1/joinevent/', game_views.JoinEventAPIView.as_view()),
    path('api/v1/submitchallenge/', game_views.SubmitChallengeAPIView.as_view()),
    path('api/v1/ranking/', game_views.RankingAPIView.as_view()),

    path('api/v1/product/', product_views.ProductAPIView.as_view()),
    path('api/v1/product/single/', product_views.ProductDetailView.as_view()),
    path('api/v1/product/buy/', product_views.ProductBuyView.as_view()),

    path('api/v1/post/', post_views.PostView.as_view()),
    path('api/v1/post/single/', post_views.PostDetailView.as_view()),
    path('api/v1/post/user/', post_views.UserPostAPIView),
    path('api/v1/post/create/', post_views.create_post),
    path('api/v1/post/edit/', post_views.edit_post),
    path('api/v1/comment/create/', post_views.create_comment),
    path('api/v1/comment/delete/', post_views.delete_comment),
    path('api/v1/like/', post_views.add_like),
]



handler404 = core.views.handle404
handler500 = core.views.handle500

# For media files like images
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

game/models.py
from django.db import models
from account.models import MyUser
from reward.models import MagicBox, Trophy

DIFFICULTY_FIELDS = (
    ('easy', 'Facile'),
    ('medium', 'Media'),
    ('hard', 'Difficile'),
)

def game_directory_path(instance, filename):
    return 'games/{}/{}'.format(instance.title, filename)

def challenge_directory_path(instance, filename):
    return 'games/{}/challenge{}/{}'.format(instance.game.title, instance.title, filename)


def user_directory_game_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'uploads/profile/user_{0}/{1}/{2}'.format(instance.user.id, instance.challenge.title, filename)

def user_directory_promotion_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'games/{}/promotions/{}'.format(instance.game.title, filename)


GAME_CHOICES = (
    ('Classic', 'Classic'),
    ('Event', 'Event')
)

OBJECT_TYPE_CHOICES = (
    ('person', 'person'),
    ('bicycle', 'bicycle'),
    ('car', 'car'),
    ('motorcycle', 'motorcycle'),
    ('airplane', 'airplane'),
    ('bus', 'bus'),
    ('train', 'train'),
    ('truck', 'truck'),
    ('boat', 'boat'),
    ('traffic light', 'traffic light'),
    ('fire hydrant', 'fire hydrant'),
    ('stop sign', 'stop sign'),
    ('parking meter', 'parking meter'),
    ('bench', 'bench'),
    ('bird', 'bird'),
    ('cat', 'cat'),
    ('dog', 'dog'),
    ('horse', 'horse'),
    ('sheep', 'sheep'),
    ('cow', 'cow'),
    ('elephant', 'elephant'),
    ('bear', 'bear'),
    ('zebra', 'zebra'),
    ('giraffe', 'giraffe'),
    ('backpack', 'backpack'),
    ('umbrella', 'umbrella'),
    ('handbag', 'handbag'),
    ('tie', 'tie'),
    ('suitcase', 'suitcase'),
    ('frisbee', 'frisbee'),
    ('skis', 'skis'),
    ('snowboard', 'snowboard'),
    ('sports ball', 'sports ball'),
    ('kite', 'kite'),
    ('baseball bat', 'baseball bat'),
    ('baseball glove', 'baseball glove'),
    ('skateboard', 'skateboard'),
    ('surfboard', 'surfboard'),
    ('tennis racket', 'tennis racket'),
    ('bottle', 'bottle'),
    ('wine glass', 'wine glass'),
    ('cup', 'cup'),
    ('fork', 'fork'),
    ('knife', 'knife'),
    ('spoon', 'spoon'),
    ('bowl', 'bowl'),
    ('banana', 'banana'),
    ('apple', 'apple'),
    ('sandwich', 'sandwich'),
    ('orange', 'orange'),
    ('broccoli', 'broccoli'),
    ('carrot', 'carrot'),
    ('hot dog', 'hot dog'),
    ('pizza', 'pizza'),
    ('donut', 'donut'),
    ('cake', 'cake'),
    ('chair', 'chair'),
    ('couch', 'couch'),
    ('potted plant', 'potted plant'),
    ('bed', 'bed'),
    ('dining table', 'dining table'),
    ('toilet', 'toilet'),
    ('tv', 'tv'),
    ('laptop', 'laptop'),
    ('mouse', 'mouse'),
    ('remote', 'remote'),
    ('keyboard', 'keyboard'),
    ('cell phone', 'cell phone'),
    ('microwave', 'microwave'),
    ('oven', 'oven'),
    ('toaster', 'toaster'),
    ('sink', 'sink'),
    ('refrigerator', 'refrigerator'),
    ('book', 'book'),
    ('clock', 'clock'),
    ('vase', 'vase'),
    ('scissors', 'scissors'),
    ('teddy bear', 'teddy bear'),
    ('hair drier', 'hair drier'),
    ('toothbrush', 'toothbrush')
)


DISTRICT_CHOICES = (
    ('Lombardy', 'Lombardy'),
    ('Non Valley', 'Non Valley'),
    ('Molo', 'Molo'),
    ('Florence', 'FLorence'),
    ('Aurora', 'Aurora'),
    ('Turro', 'Turro'),
    ('Noto', 'Noto'),
    ('Albaredo per San Marco', 'Albaredo per San Marco'),
    ('Capitoline Hill', 'Capitoline Hill'),
    ('Cannaregio', 'Cannaregio'),
    ('Milano', 'Milano'),
    ('Trentino', 'Trentino'),
    ('Roma', 'Roma'),
    ('Venezia', 'Venezia'),
    ('Agrigento', 'Agrigento'),
    ('Alessandria', 'Alessandria'),
    ('Ancona', 'Ancona'),
    ('Aosta', 'Aosta'),
    ("L'Aquila", "L'Aquila"),
    ('Arezzo', 'Arezzo'),
    ('Ascoli-Piceno', 'Ascoli-Piceno'),
    ('Asti', 'Asti'),
    ('Avellino', 'Avellino'),
    ('Bari', 'Bari'),
    ('Barletta-Andria-Trani', 'Barletta-Andria-Trani'),
    ('Belluno', 'Belluno'),
    ('Benevento', 'Benevento'),
    ('Bergamo', 'Bergamo'),
    ('Biella', 'Biella'),
    ('Bologna', 'Bologna'),
    ('Bolzano', 'Bolzano'),
    ('Brescia', 'Brescia'),
    ('Brindisi', 'Brindisi'),
    ('Cagliari', 'Cagliari'),
    ('Caltanissetta', 'Caltanissetta'),
    ('Campobasso', 'Campobasso'),
    ('Carbonia Iglesias', 'Carbonia Iglesias'),
    ('Caserta', 'Caserta'),
    ('Catania', 'Catania'),
    ('Catanzaro', 'Catanzaro'),
    ('Chieti', 'Chieti'),
    ('Como', 'Como'),
    ('Cosenza', 'Cosenza'),
    ('Cremona', 'Cremona'),
    ('Crotone', 'Crotone'),
    ('Cuneo', 'Cuneo'),
    ('Enna', 'Enna'),
    ('Fermo', 'Fermo'),
    ('Ferrara', 'Ferrara'),
    ('Firenze', 'Firenze'),
    ('Foggia', 'Foggia'),
    ('Forli-Cesena', 'Forli-Cesena'),
    ('Frosinone', 'Frosinone'),
    ('Genova', 'Genova'),
    ('Gorizia', 'Gorizia'),
    ('Grosseto', 'Grosseto'),
    ('Imperia', 'Imperia'),
    ('Isernia', 'Isernia'),
    ('La-Spezia', 'La-Spezia'),
    ('Latina', 'Latina'),
    ('Lecce', 'Lecce'),
    ('Lecco', 'Lecco'),
    ('Livorno', 'Livorno'),
    ('Lodi', 'Lodi'),
    ('Lucca', 'Lucca'),
    ('Macerata', 'Macerata'),
    ('Mantova', 'Mantova'),
    ('Massa-Carrara', 'Massa-Carrara'),
    ('Matera', 'Matera'),
    ('Medio Campidano', 'Medio Campidano'),
    ('Messina', 'Messina'),
    ('Modena', 'Modena'),
    ('Monza-Brianza', 'Monza-Brianza'),
    ('Napoli', 'Firenze'),
    ('Novara', 'Novara'),
    ('Nuoro', 'Nuoro'),
    ('Ogliastra', 'Ogliastra'),
    ('Olbia Tempio', 'Olbia Tempio'),
    ('Padova', 'Padova'),
    ('Novara', 'Novara'),
    ('Palermo', 'Palermo'),
    ('Parma', 'Parma'),
    ('Pavia', 'Pavia'),
    ('Perugia', 'Perugia'),
    ('Pesaro-Urbino', 'Pesaro-Urbino'),
    ('Pescara', 'Pescara'),
    ('Piacenza', 'Piacenza'),
    ('Pisa', 'Pisa'),
    ('Pistoia', 'Pistoia'),
    ('Ravenna', 'Ravenna'),
    ('Reggio-Calabria', 'Reggio-Calabria'),
    ('Reggio-Emilia', 'Reggio-Emilia'),
    ('Rieti', 'Rieti'),
    ('Rimini', 'Rimini'),
    ('Rovigo', 'Rovigo'),
    ('Pistoia', 'Pistoia'),
    ('Salerno', 'Salerno'),
    ('Sassari', 'Sassari'),
    ('Savona', 'Savona'),
    ('Siena', 'Siena'),
    ('Siracusa', 'Siracusa'),
    ('Sondrio', 'Sondrio'),
    ('Taranto', 'Taranto'),
    ('Terni', 'Terni'),
    ('Torino', 'Torino'),
    ('Trapani', 'Trapani'),
    ('Trento', 'Trento'),
    ('Treviso', 'Treviso'),
    ('Trieste', 'Trieste'),
    ('Udine', 'Udine'),
    ('Varese', 'Varese'),
    ('Verbania', 'Verbania'),
    ('Vercelli', 'Vercelli'),
    ('Verona', 'Verona'),
    ('Vibo-Valentia', 'Vibo-Valentia'),
    ('Vicenza', 'Vicenza'),
    ('Viterbo', 'Viterbo')
)

class Game(models.Model):
    title = models.CharField(max_length=30, unique=True)
    category = models.CharField(max_length=30, choices=GAME_CHOICES, default='Classic')
    min_players = models.IntegerField(default=0)
    total_point = models.IntegerField()
    clue = models.TextField()
    province = models.CharField(max_length=30, choices=DISTRICT_CHOICES, blank=True, null=True)
    location_name = models.CharField(max_length=300)
    location_latitude = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True)
    location_longitude = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True)
    brief = models.TextField()
    difficulty = models.CharField(max_length=6, choices=DIFFICULTY_FIELDS)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    start_date = models.DateField()
    end_date = models.DateField()
    status = models.BooleanField(default=False)
    image = models.ImageField(upload_to=game_directory_path)
    image1 = models.ImageField(upload_to=game_directory_path, null=True, blank=True)
    image2 = models.ImageField(upload_to=game_directory_path, null=True, blank=True)
    image3 = models.ImageField(upload_to=game_directory_path, null=True, blank=True)
    rules_yes = models.TextField()
    rules_no = models.TextField()
    joined_players = models.ManyToManyField(MyUser, default=None, blank=True, related_name='joined_players')

    class Meta:
        verbose_name = 'Game'
        verbose_name_plural = 'Games'

    def __str__(self):
        return self.title

    @property
    def challenges(self):
        return self.games.all()


class Challenge(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='games')
    title = models.CharField(max_length=30, unique=True)
    description = models.TextField()
    location_name = models.CharField(max_length=300)
    location_latitude = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True)
    location_longitude = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True)
    object_type = models.CharField(max_length=30, choices=OBJECT_TYPE_CHOICES, null=True, blank=True)
    clue = models.TextField()
    hint = models.TextField(null=True, blank=True)
    status = models.BooleanField(default=False)
    trophy = models.ForeignKey(Trophy, on_delete=models.SET_NULL, null=True, blank=True)
    magic_box = models.ForeignKey(MagicBox, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to=challenge_directory_path)
    image1 = models.ImageField(upload_to=challenge_directory_path, blank=True)
    image2 = models.ImageField(upload_to=challenge_directory_path, blank=True)
    image3 = models.ImageField(upload_to=challenge_directory_path, blank=True)
    # Image and Object Detection

    def __str__(self):

templates/game/delete_challenge.html
{% extends 'base.html' %}

{% block title %}
    <title>Elimina sfida</title>
{% endblock title %}

{% if form.errors %}
    {% for error in form.errors %}
        <h5>{{ error }}</h5>
    {% endfor %}
{% endif %}

{% block content %}
<div class="m-t-82">
    <div class="page_content">
        <div class="vendor_outer">
        
        <div class="vendor_title">
                <h3>Elimina sfida - {{ challenge }}</h3>
                
        </div>
        <div class="link_box">
        
            <form method="POST">
                {% csrf_token %}

                <div class="form-row mb-3">
                    <h3>Sei sicuro di voler eliminare {{ challenge }} ?</h3>
                    
                </div>              
                <h5>Dal gioco : {{ challenge.game.title }}</h5>
                <div class="mt-5">
                <button type="submit" class="btn btn-primary">Confermare</button>
                <button  class="btn btn-secondary"><a href="{% url 'game:index' %}" class=" text-white">Annulla</a></button>
                </div>
            </form>
        
        </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/game/game_details.html
{% extends 'base.html' %}

{% block title %}
<title>Dettaglio del gioco</title>
{% endblock title %}



{% block content %}	
	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			
			<div class="vendor_title">
				<h4>Dettagli dei giochi</h4>
				<a href="{% url 'game:create_game' %}"><i class="fa fa-plus"></i></a>
			</div>
			<div class="link_box">
			
			<table style="width:100%" class="table table-striped">
			
			<tbody>
			
			<tr>
			<td>Titolo</td>
			<td>{{ game.title|title }}</td>
			</tr>
			
			
			
			<tr>
			<td>Tipo di gioco</td>
			<td>{{ game.category }}</td>
			</tr>

			<tr>
				<td>Punti totali </td>
				<td>{{ game.total_point }}</td>
			</tr>

			{% if game.category == 'Event' %}
				<tr>
					<td>Partecipanti obbligatori </td>
					<td>{{ game.min_players }}</td>
				</tr>

				<tr>
					<td>I partecipanti si sono già iscritti </td>
					<td>{{ game.eventgame.total_participants }}</td>
				</tr>
			{% endif %}

			<tr>
			<td>Provincia</td>
			<td>{{ game.province }}</td>
			</tr>
			
			
			<tr>
			<td>Posizione</td>
			<td>{{ game.location_name }}</td>
			</tr>
			
			
			<tr>
			<td>Difficoltà</td>
			<td>{{ game.difficulty }}</td>
			</tr>
			
			
			
			<tr>
			<td>Descrizione del gioco </td>
			<td>{{ game.description }}</td>
			</tr>
			
			<tr>
			<td>Descrizione della posizione </td>
			<td>{{ game.description }}</td>
			</tr>
			
			
			<tr>
			<td>Data d'inizio</td>
			<td>{{ game.start_date }}</td>
			</tr>
			
			
			
			
			<tr>
			<td>Data di fine </td>
			<td>{{ game.end_date }}</td>
			</tr>
			
			
			<tr>
			<td>Regole del gioco : sì </td>
			<td>{{ game.rules_yes }}</td>
			</tr>
			
			<tr>
			<td>Regole del gioco : No </td>
			<td>{{ game.rules_no }}</td>
			</tr>
			
			<tr>
			<td>stato </td>
			<td>{{ game.status }}</td>
			</tr>

			{% if game.image %}
			<tr>
			<td>Immagine del gioco 1</td>
			<td><img src="{{ game.image.url }}" height="400px" width="400px"></td>
			</tr>
			{% endif %}
			

			{% if game.image1 %}
			<tr>
			<td>Immagine del gioco 2</td>
			<td><img src="{{ game.image1.url }}" height="400px" width="400px"></td>
			</tr>
			{% endif %}

			{% if game.image2 %}
			<tr>
			<td>Immagine del gioco 3</td>
			<td><img src="{{ game.image2.url }}" height="400px" width="400px"></td>
			</tr>
			{% endif %}

			{% if game.image3 %}
			<tr>
			<td>Immagine del gioco 4</td>
			<td><img src="{{ game.image3.url }}" height="400px" width="400px"></td>
			</tr>
			{% endif %}
		
			
			</tbody>
			</table>

			{% if promotions|length > 0 %}
			<div>
				<div class="vendor_title">
					<h4>Promozioni</h4>
					<a href="{% url 'game:create_promotion' game.id %}"><i class="fa fa-plus"></i></a>
				</div>
				{% if promotions|length == 1 %}
				<h6 class="mb-3">Nota: Ci dovrebbe essere più di una promozione per avere effetto nel gioco.</h6>
				{% endif %}
				<table style="width:100%" class="table table-striped">
					<tbody>
						{% for promotion in promotions %}
						<tr>
							<td>{{ promotion.title }} </td>
							<td>
								{{ promotion.location_latitude }}, {{ promotion.location_longitude }}
								<a class="ml-2" href="{% url 'game:edit_promotion' promotion.id %}"><i class="fa fa-edit" aria-hidden="true"></i></a> &nbsp;&nbsp;
								<a href="{% url 'game:delete_promotion' promotion.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			{% else %}
			<div class="vendor_title">
				<h4>No Promozioni</h4>
				<a href="{% url 'game:create_promotion' game.id %}"><i class="fa fa-plus"></i></a>
			</div>
			{% endif %}
			
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>
{% endblock content %}

templates/game/games.html
{% extends 'base.html' %}

{% block title %}
<title>Giochi</title>
{% endblock title %}



{% block content %}
	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			{% if messages %}
				{% for message in messages %}
					{{ message }}
				{% endfor %}
			{% endif %}
			<div class="vendor_title">
					<h4>Giochi</h4>
					<a href="{% url 'game:create_game' %}"><i class="fa fa-plus"></i></a>
				</div>
			<div class="link_box">
			
			<table id="example" class="table table-striped table-bordered" style="width:100%">
			<thead>
			<tr>
			<th>Nome del gioco </th>
			<th>Categoria </th>
			<th>Punto totale </th>
			<th>Posizione</th>
			<th>Sfide</th>
			<th></th>
			</tr>
			</thead>
			<tbody>
			
			{% for game in games %}
			<tr>
			<td>{{ game.title|title }}</td>
			<td>{{ game.category }}</td>
			<td>{{ game.total_point }}</td>
			<td>{{ game.location_name|slice:":40" }}...</td>
			<td><a href="{% url 'game:challenge' game.id %}">Elenco delle sfide</a></td>
			<td>
			<a href="{% url 'game:single' game.id %}"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp;&nbsp;
			<a href="{% url 'game:edit_game' game.id %}"><i class="fa fa-edit" aria-hidden="true"></i></a> &nbsp;&nbsp;
			<a href="{% url 'game:delete_game' game.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
			</td>
			</tr>
			{% endfor %}
			
			
			</tbody>
			</table>
			
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>
{% endblock content %}

templates/game/games_challenge.html
{% extends 'base.html' %}

{% block title %}
<title>Sfida del gioco</title>
{% endblock title %}



{% block content %}
	
	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			
			<div class="vendor_title">
					<h4>Sfida del gioco</h4>
					<a href="{% url 'game:create_challenge' game.id %}"><i class="fa fa-plus"></i></a>
				</div>
			<div class="link_box">
			
			<table id="example" class="table table-striped table-bordered" style="width:100%">
			<thead>
			<tr>
			<th>Nome del gioco </th>
			<th>Titolo della sfida </th>
			<th>Posizione</th>
			<th></th>
			</tr>
			</thead>
			<tbody>
			
			{% if challenges %}
				{% for challenge in challenges %}
				<tr>
				<td>{{ game|title }}</td>
				<td>{{ challenge.title|title }}</td>
				<td>{{ challenge.location_name|slice:":40" }}</td>
				<td>
				<a href="{% url 'game:single_challenge' challenge.id %}"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp;&nbsp;
				<a href="{% url 'game:edit_challenge' challenge.id %}"><i class="fa fa-edit" aria-hidden="true"></i></a> &nbsp;&nbsp;
				<a href="{% url 'game:delete_challenge' challenge.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
				</td>
				</tr>
				{% endfor %}
			{% else %}
				<tr>
					<td>Crea sfide per questo gioco.</td>
				</tr>
			{% endif %}
			
			
			</tbody>
			</table>
			
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>
{% endblock content %}