core/urls.py
from django.urls import path
from . import views

app_name='core'


urlpatterns = [
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout'),
    path('', views.index, name='index'),
    path('reward/', views.reward, name='reward'),
    path('settings/', views.settings, name='settings'),
    path('privacy/', views.privacy_edit, name='privacy'),
    path('conditions/', views.conditions_edit, name='conditions'),
    path('credits/', views.credits_edit, name='credits'),
]

product/urls.py
from django.urls import path
from . import views

app_name='product'


urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='single'),
    path('add/', views.add, name='add'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('category/', views.category, name='category'),
    path('addcategory/', views.add_category, name='add_category'),
    path('editcategory/<int:id>/', views.edit_category, name='edit_category'),
    path('deleteproduct/<int:id>/', views.delete_product, name='delete_product'),
    path('deletecategory/<int:id>/', views.delete_category, name='delete_category'),


    path('request/', views.product_request, name='product_request'),
    path('request/<int:id>/', views.product_request_detail, name='product_request_detail'),
    path('update/<int:id>/', views.update, name='update'),
    path('product_request_delete/<int:id>/', views.product_request_delete, name='product_request_delete'),

]

trend/urls.py
from django.contrib import admin
from django.urls import path, include

from core.api import api_views as core_views
import core

from account.api import api_views as account_views

from game.api import api_views as game_views

from post.api import api_views as post_views

from product.api import api_views as product_views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('account/', include('account.urls', namespace='account')),
    path('game/', include('game.urls', namespace='game')),
    path('post/', include('post.urls', namespace='post')),
    path('product/', include('product.urls', namespace='product')),
    path('reward/', include('reward.urls', namespace='reward')),

    
    path('password-reset/', auth_views.PasswordResetView.as_view(
        form_class = core.forms.CustomPasswordResetForm,
        template_name='core/password_reset.html',
        html_email_template_name = 'core/password_reset_html_email.html',
        subject_template_name = 'core/password_reset_subject.txt',
        from_email = 'support@trend.com'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
    ), name='password_reset_confirm'),

    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name = 'core/password_reset_complete.html'
    ), name='password_reset_complete'),

]

# API Endpoints

urlpatterns += [
	path('api/v1/login/', account_views.LoginView.as_view()),
    path('api/v1/logout/', account_views.LogoutView.as_view()),
    path('api/v1/register/', account_views.RegisterView.as_view()),
    path('api/v1/fbregister/', account_views.FacebookRegisterView.as_view()),
    path('api/v1/apple-register/', account_views.AppleRegisterAPIView.as_view()),
    path('api/v1/getverified/', account_views.GetVerifiedAPIView.as_view()),
    path('api/v1/forgotpassword/', account_views.ForgotPasswordAPIView.as_view()),
    path('api/v1/codeverification/', account_views.CodeVerificationAPIView.as_view()),
    path('api/v1/newpassword/', account_views.NewPasswordAPIView.as_view()),
    path('api/v1/updatepassword/', account_views.UpdatePasswordAPIView.as_view()),

    path('api/v1/profile/', core_views.ProfileAPIView.as_view()),
    path('api/v1/profile/follow/', core_views.FollowAPIView.as_view()),
    path('api/v1/profile/followings/', core_views.FollowingsAPIView.as_view()),
    path('api/v1/profile/dp/', core_views.ProfielDPAPIView.as_view()),
    path('api/v1/profile/update/', core_views.ProfileUpdateAPIView.as_view()),
    path('api/v1/getlist/', core_views.GetListAPIView.as_view()),
    path('api/v1/invite/', core_views.InviteAPIView.as_view()),
    path('api/v1/privacy/', core_views.PrivacyAPIView.as_view()),
    path('api/v1/conditions/', core_views.ConditionsAPIView.as_view()),
    path('api/v1/credits/', core_views.CreditsAPIView.as_view()),
    path('api/v1/completed-tours/', core_views.CompletedToursAPIView.as_view()),
    path('api/v1/ongoing-tours/', core_views.RunningToursAPIView.as_view()),

    path('api/v1/classic/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/games/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/event/', game_views.GameEventAPIView.as_view()),
    path('api/v1/game/single/', game_views.GameDetailAPIView),
    path('api/v1/game/join/', game_views.GameJoinAPIView),
    path('api/v1/challenge/', game_views.ChallengeDetailAPIView.as_view()),
    path('api/v1/joinevent/', game_views.JoinEventAPIView.as_view()),
    path('api/v1/submitchallenge/', game_views.SubmitChallengeAPIView.as_view()),
    path('api/v1/ranking/', game_views.RankingAPIView.as_view()),

    path('api/v1/product/', product_views.ProductAPIView.as_view()),
    path('api/v1/product/single/', product_views.ProductDetailView.as_view()),
    path('api/v1/product/buy/', product_views.ProductBuyView.as_view()),

    path('api/v1/post/', post_views.PostView.as_view()),
    path('api/v1/post/single/', post_views.PostDetailView.as_view()),
    path('api/v1/post/user/', post_views.UserPostAPIView),
    path('api/v1/post/create/', post_views.create_post),
    path('api/v1/post/edit/', post_views.edit_post),
    path('api/v1/comment/create/', post_views.create_comment),
    path('api/v1/comment/delete/', post_views.delete_comment),
    path('api/v1/like/', post_views.add_like),
]



handler404 = core.views.handle404
handler500 = core.views.handle500

# For media files like images
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from account.models import MyUser

def product_directory_path(instance, filename):
    return 'products/{}/{}'.format(instance.title, filename)


class ProductCategory(models.Model):
    title = models.CharField(max_length=30, unique=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=30)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    description = models.TextField()
    cost = models.IntegerField(default=0)
    points = models.IntegerField()
    hearts = models.IntegerField(default=0)
    basket = models.IntegerField(default=0)
    image = models.ImageField(upload_to=product_directory_path)

    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class ProductRequest(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='productrequests')
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='productrequests')
    fullfilled = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Function for sending the product request to the admin
    def send_request_to_admin(self):
        pass

    def __str__(self):
        return self.product.title

product/forms.py
from django import forms
from .models import Product, ProductCategory, ProductRequest

from django.forms.models import inlineformset_factory

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class ProductCategoryForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

class ProductFullfillForm(forms.ModelForm):
    class Meta:
        model = ProductRequest
        fields = ['fullfilled']

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Product, ProductCategory, ProductRequest
from .forms import ProductForm, ProductCategoryForm, ProductFullfillForm

from django.views.generic import ListView, DetailView
from trend.mixins import UserIsAdmin

from trend.decorators import admin_only
from trend.mixins import UserIsAdmin

# Product
class ProductListView(UserIsAdmin, ListView):
    model = Product
    context_object_name = 'products'
    ordering = ('-points')
    template_name = 'product/products.html'



class ProductDetailView(UserIsAdmin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'product/product_details.html'


@admin_only
def add(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        print('**************************8')
        print('got POost')
        if form.is_valid():
            print('form is valid')
            form.save()
            print('form is saved')
            title = form.cleaned_data.get('title')
            messages.success(request, f"{title} è stato aggiunto con successo!")
            return redirect('product:index')
    form = ProductForm()
    context = {
        'form': form
    }
    return render(request, 'product/create_product.html', context)


@admin_only
def edit(request, id):
    product = get_object_or_404(Product, pk=id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            title = form.cleaned_data.get('title')
            messages.success(request, f'{title} è stato modificato con successo !')
            return redirect('product:index')
        else:
            messages.error(request, 'Qualcosa è andato storto' )
    
    else:
        form = ProductForm(instance=product)
    context = {
        'form': form
    }
    return render(request, 'product/edit_product.html', context)


# Delete Product
@admin_only
def delete_product(request, id):
    product = get_object_or_404(Product, pk=id)
    if request.method == 'POST':
        Product.objects.filter(pk=id).delete()
        messages.success(request, f'Prodotto eliminato con successo!')
        return redirect('product:index')
    context = {
        'product': product
    }
    return render(request, 'product/delete_product.html', context)



# Categories
@admin_only
def category(request):
    categories = ProductCategory.objects.all()
    context = {'categories': categories}
    return render(request, 'product/product_category.html', context)



@admin_only
def add_category(request):
    if request.method == 'POST':
        form = ProductCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            title = form.cleaned_data.get('title')
            messages.success(request, f"{title} è stato aggiunto con successo!")
            return redirect('product:category')

    # categories = ProductCategory.objects.all()
    form = ProductCategoryForm()
    context = {
        'form': form,
        # 'categories': categories
    }
    return render(request, 'product/create_product_category.html', context)


@admin_only
def edit_category(request, id):
    category = get_object_or_404(ProductCategory, pk=id)
    if request.method == 'POST':
        form = ProductCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, f"La categoria è stata aggiornata con successo!")
            return redirect('product:category')

    else:
        form = ProductCategoryForm(instance=category)
    context = {
        'form': form,
        'category': category
    }
    return render(request, 'product/edit_product_category.html', context)


# Delete Product
@admin_only
def delete_category(request, id):
    category = get_object_or_404(ProductCategory, pk=id)
    products = Product.objects.filter(category=category).count()
    if request.method == 'POST':
        category.delete()
        messages.success(request, f"La categoria è stata eliminata con successo!")
        return redirect('product:index')
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'product/delete_category.html', context)




# Product Request
@admin_only
def product_request(request):
    product_requests = ProductRequest.objects.all().order_by('-created_at')
    context = {
        'product_requests': product_requests,
    }
    return render(request, 'product/product_requests.html', context)


@admin_only
def product_request_detail(request, id):
    product_request = get_object_or_404(ProductRequest, pk=id)
    context = {
        'product_request': product_request,
    }
    return render(request, 'product/product_request_detail.html', context)


@admin_only
def update(request, id):
    product_request = get_object_or_404(ProductRequest, pk=id)
    if request.POST:
        form = ProductFullfillForm(request.POST, instance=product_request)
        if form.is_valid():
            form.save()
            messages.success(request, f"La richiesta del prodotto è stata aggiornata correttamente!")
            return redirect('product:product_request')
    else:
        form = ProductFullfillForm(instance=product_request)

    context = {
        'product_request': product_request,
        'form': form
    }

    return render(request, 'product/edit_product_request.html', context)


@admin_only
def product_request_delete(request, id):
    product_request = get_object_or_404(ProductRequest, pk=id)
    if request.method == 'POST':
        product_request.delete()
        messages.success(request, f"La richiesta del prodotto è stata eliminata correttamente!")
        return redirect('product:product_request')
    context = {
        'product_request': product_request
    }
    return render(request, 'product/delete_product_request.html', context)

templates/product/add_category.html
{% extends 'base.html' %}

{% block title %}
    <title>Aggiungi categoria</title>
{% endblock title %}

{% if form.errors %}
    {% for error in form.errors %}
        <h5>{{ error }}</h5>
    {% endfor %}
{% endif %}

{% block content %}
    <h1>This is Product page</h1>

<div class="row">
    <div class="col-sm-3">
        hello
    </div>
    <div class="col-sm-9">
        <h3>Add Category</h3>
        <label for="cars"> Old Categories:</label>

        <select name="product_category" id="product_category">
            {% for category in categories %}
          <option value="{{ category }}">{{ category }}</option>
            {% endfor %}
        </select>


        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
        
    </div>
</div>
{% endblock content %}

templates/product/create_product.html
{% extends 'base.html' %}	

{% block title %}
<title>Crea prodotto</title>
{% endblock title %}

{% block content %}

	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			
			<div class="vendor_title">
					<h4>Crea prodotto</h4>
					
				</div>
			<div class="link_box">
			
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					
					<div class="form-row">
					<div class="form-group col-md-6">
						<label> Nome</label>
						{{ form.title }}
						
					</div>
					<div class="form-group col-md-6">
						<label> Categoria</label>
						<!-- <select class="form-control"> -->
						{{ form.category }}
						</select>
					</div>
					<!-- <select name="category" class="select form-control" required="" id="id_category">
						<option value="">---------</option> 
						<option value="1" selected="">Nike</option>
						<option value="2">Reboot</option>

					</select> -->
					
					</div>

					
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>Costo</label>
							{{ form.cost }}
						</div>
						<div class="form-group col-md-6">
							<label>Credito</label>
							{{ form.points }}
						</div>
					</div>
						
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>Piace</label>
							{{ form.hearts }}
						</div>
						<div class="form-group col-md-6">
							<label>Cestino</label>
							{{ form.basket }}
						</div>
					</div>
					
					<div class="form-row mt-4">
					<div class="form-group col-md-12">
						<label>Descrizione </label>
						{{ form.description }}
					</div>
					
					</div>
					
			
			
					
					<div class="form-row">
					<div class="form-group col-md-12">
						<label for="inputEmail4">immagini</label>
						{{ form.image }}
	
					</div>
					</div>
					
					<div class="form-group">
					<div class="form-check">
						{{ form.is_active }}
						<label class="form-check-label" for="gridCheck">
							Attiva
						</label>
					</div>
					</div>
					
				
					<button type="submit" class="btn btn-primary">Crea prodotto</button>
				</form>
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>
{% endblock content %}

{% block script %}
<script>
	var inputs = document.getElementsByTagName('input')
	console.log(inputs)

	for(i=0;i<inputs.length;i++){
		inputs[i].className += 'form-control'
	}

	document.getElementsByTagName('textarea')[0].className += 'form-control'
	var active = document.getElementById('id_is_active')
	active.className = 'form-check-label'
	active.id += 'gridCheck'

	var active = document.getElementById('id_category')
	active.className += 'select form-control'

	document.getElementById('id_image').required = true;
</script>
{% endblock script %}

templates/product/create_product_category.html
{% extends 'base.html' %}

{% block title %}
{% if category %}
	<label>Aggiorna categoria:</label>
	{% else %}
	<label>Crea categoria :</label>
	{% endif %}
{% endblock title %}


{% block content %}
				
				<div class="m-t-82">
					<div class="page_content">
						<div class="vendor_outer">
						
						<div class="vendor_title">
								<h4>categoria di prodotto</h4>
								
							</div>
						<div class="link_box">
						
							<form method="POST">
								{% csrf_token %}
								<!-- {{ form }} -->
							  
							    <div class="form-row">
								<div class="form-group col-md-6">
									{% if category %}
									<label>Cambia categoria "{{ category }}" nome a :</label>
									{% else %}
									<label>Nome della categoria :</label>
									{% endif %}
								  <input type="text" class="form-control" placeholder="Category Name" required name="title">
								</div>
								
								</div>
							
							  <button type="submit" class="btn btn-primary">Aggiorna categoria</button>
							</form>
						
						</div>
						</div>
					</div>
					<div class="footer">
						<p>Copyright © 2020. </p>
					</div>
				</div>
{% endblock content %}

templates/product/delete_category.html
{% extends 'base.html' %}

{% block title %}
    <title>Elimina categoria</title>
{% endblock title %}

{% if form.errors %}
    {% for error in form.errors %}
        <h5>{{ error }}</h5>
    {% endfor %}
{% endif %}

{% block content %}
<div class="m-t-82">
    <div class="page_content">
        <div class="vendor_outer">
        
        <div class="vendor_title">
                <h3>Elimina categoria prodotto - {{ category }}</h3>
                
        </div>
        <div class="link_box">
        
            <form method="POST">
                {% csrf_token %}

                <div class="form-row mb-3">
                    <h3>Sei sicuro di voler eliminare {{ category }} ?</h3>
                    
                </div>
                <h5>Costo: verrà anche eliminato {{ products }} Prodotto(ti).</h5>
                <div class="mt-5">
                <button type="submit" class="btn btn-primary">Confermare</button>
                <button  class="btn btn-secondary"><a href="{% url 'product:category' %}" class=" text-white">Annulla</a></button>
                </div>
            </form>
        
        </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/product/delete_product.html
{% extends 'base.html' %}

{% block title %}
    <title>Elimina prodotto</title>
{% endblock title %}

{% if form.errors %}
    {% for error in form.errors %}
        <h5>{{ error }}</h5>
    {% endfor %}
{% endif %}

{% block content %}
<div class="m-t-82">
    <div class="page_content">
        <div class="vendor_outer">
        
        <div class="vendor_title">
                <h3>Elimina prodotto - {{ product }}</h3>
                
        </div>
        <div class="link_box">
        
            <form method="POST">
                {% csrf_token %}

                <div class="form-row mb-3">
                    <h3>Sei sicuro di voler eliminare {{ product }} ?</h3>
                    
                </div>              
                <h5>Categoria: {{ product.category }}</h5>
                <h5>Costo: {{ product.cost }}</h5>
                <h5>Punti: {{ product.point }}</h5>
                <div class="mt-5">
                <button type="submit" class="btn btn-primary">Confermare</button>
                <button  class="btn btn-secondary"><a href="{% url 'product:index' %}" class=" text-white">Annulla</a></button>
                </div>
            </form>
        
        </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/product/edit_product.html
{% extends 'base.html' %}	

{% block title %}
<title>Modifica prodotto</title>
{% endblock title %}

{% block content %}

	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			
			<div class="vendor_title">
					<h4>Modifica prodotto</h4>
					
				</div>
			<div class="link_box">
			
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					
					<div class="form-row">
					<div class="form-group col-md-6">
						<label> Nome</label>
						{{ form.title }}
						
					</div>
					<div class="form-group col-md-6">
						<label> Categoria</label>
						<!-- <select class="form-control"> -->
						{{ form.category }}
						</select>
					</div>
					<!-- <select name="category" class="select form-control" required="" id="id_category">
						<option value="">---------</option> 
						<option value="1" selected="">Nike</option>
						<option value="2">Reboot</option>

					</select> -->
					
					</div>

					
					<div class="form-row">
					<div class="form-group col-md-6">
						<label>Costo</label>
						{{ form.cost }}
					</div>
					<div class="form-group col-md-6">
						<label>Credito</label>
						{{ form.points }}
					</div>
					</div>
					
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>Piace</label>
							{{ form.hearts }}
						</div>
						<div class="form-group col-md-6">
							<label>Cestino</label>
							{{ form.basket }}
						</div>
					</div>
					
					<div class="form-row mt-4">
					<div class="form-group col-md-12">
						<label>Descrizione </label>
						{{ form.description }}
					</div>
					
					</div>
					
			
			
					
					<div class="form-row">
					<div class="form-group col-md-12">
						<label for="inputEmail4">immagini</label>
						{{ form.image }}
					</div>
					</div>
					
					<div class="form-group">
					<div class="form-check">
						{{ form.is_active }}
						<label class="form-check-label" for="gridCheck">
							Attiva
						</label>
					</div>
					</div>
					
				

					<button type="submit" class="btn btn-primary">Modifica prodotto</button>
				</form>
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>
{% endblock content %}

{% block script %}
<script>
	var inputs = document.getElementsByTagName('input')
	console.log(inputs)

	for(i=0;i<inputs.length;i++){
		inputs[i].className += 'form-control'
	}

	document.getElementsByTagName('textarea')[0].className += 'form-control'
	var active = document.getElementById('id_is_active')
	active.className = 'form-check-label'
	active.id += 'gridCheck'

	var active = document.getElementById('id_category')
	active.className += 'select form-control'
	
	document.getElementById('id_image').required = false;

</script>
{% endblock script %}

templates/product/edit_product_category.html
{% extends 'base.html' %}

{% block title %}
<title>Modifica categoria prodotto</title>
{% endblock title %}


{% block content %}
				
				<div class="m-t-82">
					<div class="page_content">
						<div class="vendor_outer">
						
						<div class="vendor_title">
								<h4>Modifica categoria prodotto</h4>
								
							</div>
						<div class="link_box">
						
							<form method="POST">
								{% csrf_token %}
								<!-- {{ form }} -->
							  
							    <div class="form-row">
								<div class="form-group col-md-6">
									{% if category %}
									<label>Cambia categoria "{{ category }}" name to :</label>
									{% else %}
									<label>Nome della categoria :</label>
									{% endif %}
								  <input type="text" value="{{ form.title.value }}" class="form-control" placeholder="Category Name" name="title">
								</div>
								
								</div>
							
							  <button type="submit" class="btn btn-primary">Aggiorna categoria</button>
							</form>
						
						</div>
						</div>
					</div>
					<div class="footer">
						<p>Copyright © 2020. </p>
					</div>
				</div>
{% endblock content %}

templates/product/product_category.html
{% extends 'base.html' %}

{% block title %}
<title>Categorie di Prodotto</title>
{% endblock title %}

{% block content %}
				
	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			{% if messages %}
				{% for message in messages %}
					{{ message }}
				{% endfor %}
			{% endif %}
			<div class="vendor_title">
					<h4>categoria di prodotto</h4>
					<a href="{% url 'product:add_category' %}"><i class="fa fa-plus"></i></a>
				</div>
			<div class="link_box">
			
			<table id="example" class="table table-striped table-bordered" style="width:100%">
			<thead>
			<tr>
			<th>ID categoria </th>
			<th>Nome della categoria</th>
			
			<th></th>
			</tr>
			</thead>
			<tbody>

			{% for category in categories %}
			<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ category|title }}</td>
			<td>
			<a href="{% url 'product:edit_category' category.id %}"><i class="fa fa-edit" aria-hidden="true"></i></a> &nbsp;&nbsp;
			<a href="{% url 'product:delete_category' category.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
			</td>
			</tr>
			{% endfor %}
			
			
			</tbody>
			</table>
			
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>

{% endblock content %}

templates/product/product_request_1.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Admin</title>
{% endblock title %}


{% block content %}
    <h1>This is Product page</h1>

<div class="row">
    <div class="col-sm-3">
        hello
    </div>
    <div class="col-sm-9">
        <form method="get">
            {{ myfilter.form }}
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
        <h3>Requests</h3>
        <ul class="list-group">
            {% for req in requests %}
            {% if not req.fullfilled %}
            <li class="list-group-item">
                <a href="{% url 'product:single' req.product.id %}">{{ req }}</a>
                <h4>Category: {{ req.user.username }}</h4>
                <h4>Category: {{ req.quantity }}</h4>
                <a href="{% url 'product:fullfil' req.id %}"><button class="btn btn-primary">fullfil</button></a>
                <a href="{% url 'product:product_request_delete' req.id %}"><button class="btn btn-danger">Delete</button></a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        <hr>
        <h3>Fullfilled Requests</h3>
        <ul class="list-group">
            {% for req in requests %}
            {% if req.fullfilled %}
            <li class="list-group-item">
                <a href="{% url 'product:single' req.product.id %}">{{ req }}</a>
                <h4>Category: {{ req.user.username }}</h4>
                <h4>Category: {{ req.quantity }}</h4>
                <a href="{% url 'product:unfullfil' req.id %}"><button class="btn btn-warning">unfullfil</button></a>
                <a href="{% url 'product:product_request_delete' req.id %}"><button class="btn btn-danger">Delete</button></a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>

    </div>
</div>

<script src="{% static 'js/date.js' %}"></script>
{% endblock content %}

templates/product/product_requests.html
{% extends 'base.html' %}	
	
{% block title %}
<title>Richieste</title>
{% endblock title %}

{% block content %}

	<div class="m-t-82">
		<div class="page_content">
			<div class="vendor_outer">
			{% if messages %}
				{% for message in messages %}
					{{ message }}
				{% endfor %}
			{% endif %}
			<div class="vendor_title">
					<h4>Richieste</h4>
			</div>
			<div class="link_box">
			
			<table id="example" class="table table-striped table-bordered" style="width:100%">
			<thead>
			<tr>
			<th>Nome </th>
			<th>Di </th>
			<th>Creato a</th>
			<th>Stato pieno</th>
			<th></th>
			</tr>
			</thead>
			<tbody>
			
			{% for product in product_requests %}
			<tr>
			<td><a href="{% url 'product:single' product.product.id %}">{{ product }}</a></td>
			<td><a href="{% url 'account:edit' product.user.id %}">{{ product.user.email }}</a></td>
			<td>{{ product.created_at}}</td>
			<td>{{ product.fullfilled }}</td>
			<td>
			<a href="{% url 'product:product_request_detail' product.id %}"><i class="fa fa-eye" aria-hidden="true"></i></a>&nbsp;&nbsp;
			<a href="{% url 'product:update' product.id %}"><i class="fa fa-edit" aria-hidden="true"></i></a> &nbsp;&nbsp;
			<a href="{% url 'product:product_request_delete' product.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
			</td>
			</tr>
			{% endfor %}
			
			
			</tbody>
			</table>
			
			
			</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright © 2020. </p>
		</div>
	</div>

{% endblock content %}