account/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='account'


urlpatterns = [
    path('', views.admin_users, name='admin_users'),
    path('create_admin/', views.create_admin, name='create_admin'),
    path('users', views.users, name='users'),
    path('create_user/', views.create_user, name='create_user'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

core/urls.py
from django.urls import path
from . import views

app_name='core'


urlpatterns = [
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout'),
    path('', views.index, name='index'),
    path('reward/', views.reward, name='reward'),
    path('settings/', views.settings, name='settings'),
    path('privacy/', views.privacy_edit, name='privacy'),
    path('conditions/', views.conditions_edit, name='conditions'),
    path('credits/', views.credits_edit, name='credits'),
]

product/urls.py
from django.urls import path
from . import views

app_name='product'


urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='single'),
    path('add/', views.add, name='add'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('category/', views.category, name='category'),
    path('addcategory/', views.add_category, name='add_category'),
    path('editcategory/<int:id>/', views.edit_category, name='edit_category'),
    path('deleteproduct/<int:id>/', views.delete_product, name='delete_product'),
    path('deletecategory/<int:id>/', views.delete_category, name='delete_category'),


    path('request/', views.product_request, name='product_request'),
    path('request/<int:id>/', views.product_request_detail, name='product_request_detail'),
    path('update/<int:id>/', views.update, name='update'),
    path('product_request_delete/<int:id>/', views.product_request_delete, name='product_request_delete'),

]

reward/urls.py
from django.urls import path
from . import views

app_name = 'reward'

urlpatterns = [
    path('trophies/', views.trophies, name="trophies"),
    path('trophies/detail/<int:id>/', views.trophy_detail, name="trophy_detail"),
    path('trophies/create/', views.create_trophy, name="create_trophy"),
    path('trophies/update/<int:id>/', views.update_trophy, name="update_trophy"),
    path('trophies/delete/<int:id>/', views.delete_trophy, name="delete_trophy"),
    path('magic_box/', views.magic_boxes, name="magic_boxes"),
    path('magic_box/<int:id>/', views.magic_box_detail, name="magic_box_detail"),
    path('magic_box/create/', views.create_magic_boxes, name="create_magic_box"),
    path('magic_box/update/<int:id>/', views.update_magic_boxes, name="update_magic_box"),
    path('magic_box/delete/<int:id>/', views.delete_magic_boxes, name="delete_magic_box"),
]

trend/urls.py
from django.contrib import admin
from django.urls import path, include

from core.api import api_views as core_views
import core

from account.api import api_views as account_views

from game.api import api_views as game_views

from post.api import api_views as post_views

from product.api import api_views as product_views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('account/', include('account.urls', namespace='account')),
    path('game/', include('game.urls', namespace='game')),
    path('post/', include('post.urls', namespace='post')),
    path('product/', include('product.urls', namespace='product')),
    path('reward/', include('reward.urls', namespace='reward')),

    
    path('password-reset/', auth_views.PasswordResetView.as_view(
        form_class = core.forms.CustomPasswordResetForm,
        template_name='core/password_reset.html',
        html_email_template_name = 'core/password_reset_html_email.html',
        subject_template_name = 'core/password_reset_subject.txt',
        from_email = 'support@trend.com'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
    ), name='password_reset_confirm'),

    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name = 'core/password_reset_complete.html'
    ), name='password_reset_complete'),

]

# API Endpoints

urlpatterns += [
	path('api/v1/login/', account_views.LoginView.as_view()),
    path('api/v1/logout/', account_views.LogoutView.as_view()),
    path('api/v1/register/', account_views.RegisterView.as_view()),
    path('api/v1/fbregister/', account_views.FacebookRegisterView.as_view()),
    path('api/v1/apple-register/', account_views.AppleRegisterAPIView.as_view()),
    path('api/v1/getverified/', account_views.GetVerifiedAPIView.as_view()),
    path('api/v1/forgotpassword/', account_views.ForgotPasswordAPIView.as_view()),
    path('api/v1/codeverification/', account_views.CodeVerificationAPIView.as_view()),
    path('api/v1/newpassword/', account_views.NewPasswordAPIView.as_view()),
    path('api/v1/updatepassword/', account_views.UpdatePasswordAPIView.as_view()),

    path('api/v1/profile/', core_views.ProfileAPIView.as_view()),
    path('api/v1/profile/follow/', core_views.FollowAPIView.as_view()),
    path('api/v1/profile/followings/', core_views.FollowingsAPIView.as_view()),
    path('api/v1/profile/dp/', core_views.ProfielDPAPIView.as_view()),
    path('api/v1/profile/update/', core_views.ProfileUpdateAPIView.as_view()),
    path('api/v1/getlist/', core_views.GetListAPIView.as_view()),
    path('api/v1/invite/', core_views.InviteAPIView.as_view()),
    path('api/v1/privacy/', core_views.PrivacyAPIView.as_view()),
    path('api/v1/conditions/', core_views.ConditionsAPIView.as_view()),
    path('api/v1/credits/', core_views.CreditsAPIView.as_view()),
    path('api/v1/completed-tours/', core_views.CompletedToursAPIView.as_view()),
    path('api/v1/ongoing-tours/', core_views.RunningToursAPIView.as_view()),

    path('api/v1/classic/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/games/', game_views.GameClassicAPIView.as_view()),
    path('api/v1/event/', game_views.GameEventAPIView.as_view()),
    path('api/v1/game/single/', game_views.GameDetailAPIView),
    path('api/v1/game/join/', game_views.GameJoinAPIView),
    path('api/v1/challenge/', game_views.ChallengeDetailAPIView.as_view()),
    path('api/v1/joinevent/', game_views.JoinEventAPIView.as_view()),
    path('api/v1/submitchallenge/', game_views.SubmitChallengeAPIView.as_view()),
    path('api/v1/ranking/', game_views.RankingAPIView.as_view()),

    path('api/v1/product/', product_views.ProductAPIView.as_view()),
    path('api/v1/product/single/', product_views.ProductDetailView.as_view()),
    path('api/v1/product/buy/', product_views.ProductBuyView.as_view()),

    path('api/v1/post/', post_views.PostView.as_view()),
    path('api/v1/post/single/', post_views.PostDetailView.as_view()),
    path('api/v1/post/user/', post_views.UserPostAPIView),
    path('api/v1/post/create/', post_views.create_post),
    path('api/v1/post/edit/', post_views.edit_post),
    path('api/v1/comment/create/', post_views.create_comment),
    path('api/v1/comment/delete/', post_views.delete_comment),
    path('api/v1/like/', post_views.add_like),
]



handler404 = core.views.handle404
handler500 = core.views.handle500

# For media files like images
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
        {% block title %}
        <title>Trend</title>
        {% endblock title %}
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
		<link href="{% static 'css/fonts/font.css' %}" type="text/css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.css"/>
		<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.js"></script>
	</head>
	<body>
		<section class="page_outer">
			<div class="sidebar">
				<div class="logo">
							<div class="toggle_menu">
								<img src="{% static 'images/toogle.png' %}" align="">
							</div>
				</div>
				<div class="menu">
					<ul>
						<li class="{% if admin_active or what == 'admin' %}active{% endif %}">
							<a href="{% url 'account:admin_users' %}"> <i class="fa fa-user-plus"></i>
							<span>Utenti amministratori</span>
							</a>
						</li>
						<li class="{% if user_active or what == 'norm' %}active{% endif %}">
							<a href="{% url 'account:users' %}"> <i class="fa fa-user"></i>
							<span>Utenti</span>
							</a>
						</li>
						<li class="{% if 'game' in request.get_full_path and 'category' not in request.get_full_path %}active{% endif %}">
							<a href="{% url 'game:index' %}"><i class="fa fa-gamepad" aria-hidden="true"></i>

								<span>Tour del gioco</span>
							</a>
						</li>
						
						<li class="{% if 'product' in request.get_full_path and 'category' in request.get_full_path %}active{% endif %}">
							<a href="{% url 'product:category' %}"><i class="fa fa-list-alt" aria-hidden="true"></i>
							<span>Categorie di Prodotto</span>
							</a>
						</li>
						
						<li class="{% if 'product' in request.get_full_path and 'product/request' not in request.get_full_path and 'product/update' not in request.get_full_path and 'product/product_request_delete' not in request.get_full_path and 'category' not in request.get_full_path %}active{% endif %}">
							<a href="{% url 'product:index' %}">
								<i class="fa fa-product-hunt"></i>
								<span>Prodotti</span>
							</a>
						</li>
						
						<li class="{% if 'request' in request.get_full_path or 'product/update' in request.get_full_path or 'product/product_request_delete' in request.get_full_path and 'category' not in request.get_full_path %}active{% endif %}">
							<a href="{% url 'product:product_request' %}">
								<i class="fa fa-product-hunt"></i>
								<span>Richieste di prodotti</span>
							</a>
						</li>
						
						<li class="{% if 'post' in request.get_full_path and 'category' not in request.get_full_path %}active{% endif %}">
							<a href="{% url 'post:index' %}">
								<i class="fa fa-product-hunt"></i>
								<span>Pubblica</span>
							</a>
						</li>
						
						<li class="{% if 'trophies' in request.get_full_path and 'category' not in request.get_full_path %}active{% endif %}">
							<a href="{% url 'reward:trophies' %}">
								<i class="fa fa-product-hunt"></i>
								<span>Trofei</span>
							</a>
						</li>
						
						<li class="{% if 'magic_box' in request.get_full_path and 'category' not in request.get_full_path %}active{% endif %}">
							<a href="{% url 'reward:magic_boxes' %}">
								<i class="fa fa-product-hunt"></i>
								<span>Scatole magiche</span>
							</a>
						</li>
						
						<li class="{% if 'settings' in request.get_full_path and 'category' not in request.get_full_path %}active{% endif %}">
							<a href="{% url 'core:settings' %}">
								<i class="fa fa-cog"></i>
								<span>impostazioni</span>
							</a>
						</li>
						
					</ul>
				</div>
			
			</div>
			<div class="content_part">
				<div class="header d-new-a">
					<div class="header_left">
							<div class="toggle_menu">
								<img src="{% static 'images/toogle.png' %}" align="">
							</div>
						
					</div>
					<div class="header_right d-align">
						<div class="notification user_notification">
							<a href="#">
								<i class="fa fa-cog" aria-hidden="true"></i>
							</a>
							
						</div>
						<div class="header_user">
							<a href="{% url 'core:logout' %}">
								Disconnettersi
							</a>
						</div>
					</div>
                </div>
                {% if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                {% endif %}

                
                {% block content %}
                {% endblock content %}

            </div>
		</section>
		<div class="modal" id="modal">
			<div class="modal-dialog modal-lg modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<div class="model_video">
			        		<iframe src="" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
			        	</div>
					</div>
				</div>
			</div>
		</div>
		<div class="modal" id="modal1">
			<div class="modal-dialog modal-lg modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<div class="noti_modal_info">
							<h3>Nofification 01</h3>
							<div class="noti_modal_img">
								<img src="images/content_img.png" alt="">
							</div>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac auctor augue mauris augue. A cras semper auctor neque vitae tempus quam pellentesque nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac auctor augue mauris augue. A cras semper auctor neque vitae tempus quam pellentesque nec.</p>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac auctor augue mauris augue. A cras semper auctor neque vitae tempus quam pellentesque nec.</p>
						</div>
					</div>
				</div>
			</div>
        </div>
        
        {% block script %}
        {% endblock script %}
		<script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.css"/>
		<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.js"></script>
		<script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
		<script type="text/javascript">
		$(document).ready(function() {
		$('#example').DataTable();
		} );
		</script>
		
	</body>
</html>